language: ruby

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

rvm:
  - 2.1

env:
  global:
    - AWS_ACCESS_KEY_ID=abc123
    - AWS_SECRET_ACCESS_KEY=abc123
    - AWS_S3_BUCKET=abc123

notifications:
  email: false
